
const backendBaseUrl=  "http://localhost:5000/api";
const urlBuilder = {
    authBaseUrl: "/auth",
    login: "/login",
    refresh: "/refresh",
    studentsBaseUrl: "/students",
    commentsBaseUrl: "/comments",
    groupsBaseUrl: "/groups",
    registerManager: "/registerManager",
    logout: "/logout",
    getAllManagers: "/getManager",
    getAllManagersFull: "/getManagerFull",
    getMe:"/me",
    manager:"/manager",
    verify:"/verify",
    createPassword:"/addPassword",
    sendActivateEmail:"/sendActivateEmail",
    forgotPassword:"/password/forgot",
    banManager:"/banManager",
    unbanManager:"/unbanManager",
    studentStatistics:"/statistics",
    createComment:"/createComment",
    createGroup:"/createGroup",
    loginUrl:() =>  backendBaseUrl + urlBuilder.authBaseUrl + urlBuilder.login,
    refreshUrl:() =>  backendBaseUrl + urlBuilder.authBaseUrl + urlBuilder.refresh,
    registerManagerUrl:() => backendBaseUrl + urlBuilder.authBaseUrl + urlBuilder.registerManager,
    logoutUrl:() => backendBaseUrl + urlBuilder.authBaseUrl + urlBuilder.logout,
    getMeUrl:() =>  backendBaseUrl + urlBuilder.authBaseUrl + urlBuilder.getMe,
    getAllManagerUrl:() => backendBaseUrl + urlBuilder.authBaseUrl + urlBuilder.getAllManagers,
    getAllManagerFullUrl:() => backendBaseUrl + urlBuilder.authBaseUrl + urlBuilder.getAllManagersFull,
    verifyUrl:() => backendBaseUrl + urlBuilder.authBaseUrl + urlBuilder.verify,
    createPasswordUrl:() => backendBaseUrl + urlBuilder.authBaseUrl + urlBuilder.createPassword,
    sendActivateEmailUrl:() => backendBaseUrl + urlBuilder.authBaseUrl + urlBuilder.sendActivateEmail,
    forgotPasswordUrl:() => backendBaseUrl + urlBuilder.authBaseUrl + urlBuilder.forgotPassword,
    banManagerUrl:() => backendBaseUrl + urlBuilder.authBaseUrl + urlBuilder.banManager,
    unbanManagerUrl:() => backendBaseUrl + urlBuilder.authBaseUrl + urlBuilder.unbanManager,
    getManagerByIdUrl:() => backendBaseUrl + urlBuilder.authBaseUrl + urlBuilder.manager,
    getAllStudentUrl:() => backendBaseUrl + urlBuilder.studentsBaseUrl,
    getStudentStatisticsUrl:() => backendBaseUrl + urlBuilder.studentsBaseUrl +urlBuilder.studentStatistics,
    createCommentUrl:() => backendBaseUrl + urlBuilder.commentsBaseUrl + urlBuilder.createComment,
    getAllCommentsByStudentIdUrl:() => backendBaseUrl + urlBuilder.commentsBaseUrl,
    updateStudentUrl:() => backendBaseUrl + urlBuilder.studentsBaseUrl,
    createGroupUrl:() => backendBaseUrl + urlBuilder.groupsBaseUrl + urlBuilder.createGroup,
    getAllGroupUrl:() => backendBaseUrl + urlBuilder.groupsBaseUrl,
    updateGroupUrl:() => backendBaseUrl + urlBuilder.groupsBaseUrl,
}
export {
    backendBaseUrl,
    urlBuilder,
}